name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    strategy:
      matrix:
        arch:
          - arm64
          - armhf

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - uses: addnab/docker-run-action@v3
        with:
          image: clickable/ci-20.04-${{ matrix.arch }}
          options: -v ${{ github.workspace }}:/work
          run: cd /work && clickable build --arch=${{ matrix.arch }} --output=dist-${{ matrix.arch }} --container-mode

      - uses: actions/upload-artifact@v7
        with:
          name: podphoenix-${{ matrix.arch }}
          path: dist-${{ matrix.arch }}/*
